name: Docker Test

on:
  push:
    branches:
      - "abrown/docker-for-tests"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: composerci.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Docker Build
        run: docker build -f Dockerfile.Test -t ${{ secrets.ACR_USERNAME }}.azurecr.io/composer/ci:${{ github.sha }} .
      - name: Docker push
        run: docker push  ${{ secrets.ACR_USERNAME }}.azurecr.io/composer/ci:${{ github.sha }}
